### ISSUE TITLE
gitian-build fails on ubuntu 18.04

### ISSUE THREAD

**Issue by sipsorcery** [bitcoin-core/gitian.sigs#923]
I've been attempting to setup the gitian build environment on an Ubuntu 18.0.4.1 LTS virtual machine but am hitting a roadblock on the `./gitian-build.py --detach-sign --no-commit -b satoshi 0.16.0rc1` step which in my case I am executing as `./gitian-build.py --detach-sign --no-commit -b sipsorcery 0.17.1rc1`.

I've create the vm from scratch 3 times and followed the instructions at https://github.com/bitcoin-core/docs/blob/master/gitian-building.md and https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-setup-gitian-debian.md but each time I end up with the errors below when executing the above command:

```
gitianuser@btc-gitian:~$ ./gitian-build.py --detach-sign --no-commit -b sipsorcery 0.17.1rc1
Cannot build for MacOS, SDK does not exist. Will build for other OSes
v0.17.1rc1
HEAD is now at ef70f9b52 doc: Fill in authors and changelog for 0.17.1 release notes

Building Dependencies

--2018-12-19 21:00:34--  http://downloads.sourceforge.net/project/osslsigncode/osslsigncode/osslsigncode-1.7.1.tar.gz
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://kent.dl.sourceforge.net/project/osslsigncode/osslsigncode/osslsigncode-1.7.1.tar.gz [following]
--2018-12-19 21:00:34--  https://kent.dl.sourceforge.net/project/osslsigncode/osslsigncode/osslsigncode-1.7.1.tar.gz
Resolving kent.dl.sourceforge.net (kent.dl.sourceforge.net)... 212.219.56.185
Connecting to kent.dl.sourceforge.net (kent.dl.sourceforge.net)|212.219.56.185|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘inputs/osslsigncode-1.7.1.tar.gz’ not modified on server. Omitting download.

--2018-12-19 21:00:34--  https://bitcoincore.org/cfields/osslsigncode-Backports-to-1.7.1.patch
Resolving bitcoincore.org (bitcoincore.org)... 198.251.83.116, 107.191.99.5
Connecting to bitcoincore.org (bitcoincore.org)|198.251.83.116|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘inputs/osslsigncode-Backports-to-1.7.1.patch’ not modified on server. Omitting download.

make: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Leaving directory '/home/gitianuser/bitcoin/depends'
make[1]: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Leaving directory '/home/gitianuser/bitcoin/depends'
make[1]: Entering directory '/home/gitianuser/bitcoin/depends'
make[1]: Leaving directory '/home/gitianuser/bitcoin/depends'
make: Leaving directory '/home/gitianuser/bitcoin/depends'

Compiling 0.17.1rc1 Linux
--- Building for bionic amd64 ---
Stopping target if it is up
Making a new image copy
lxc-execute: gitian: start.c: lxc_spawn: 1616 Failed to find gateway addresses
                                                                              lxc-execute: gitian: start.c: __lxc_start: 1939 Failed to spawn container "gitian"
                                        lxc-execute: gitian: tools/lxc_execute.c: main: 245 Failed run an application inside container
Traceback (most recent call last):
        6: from bin/gbuild:302:in `<main>'
        5: from bin/gbuild:302:in `each'
        4: from bin/gbuild:304:in `block in <main>'
        3: from bin/gbuild:304:in `each'
        2: from bin/gbuild:309:in `block (2 levels) in <main>'
        1: from bin/gbuild:58:in `build_one_configuration'
bin/gbuild:21:in `system!': failed to run make-clean-vm --suite bionic --arch amd64 (RuntimeError)
Traceback (most recent call last):
  File "./gitian-build.py", line 231, in <module>
    main()
  File "./gitian-build.py", line 222, in main
    build()
  File "./gitian-build.py", line 60, in build
    subprocess.check_call(['bin/gbuild', '-j', args.jobs, '-m', args.memory, '--commit', 'bitcoin='+args.commit, '--url', 'bitcoin='+args.url, '../bitcoin/contrib/gitian-descriptors/gitian-linux.yml'])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/gbuild', '-j', '2', '-m', '2000', '--commit', 'bitcoin=v0.17.1rc1', '--url', 'bitcoin=https://github.com/bitcoin/bitcoin', '../bitcoin/contrib/gitian-descriptors/gitian-linux.yml']' returned non-zero exit status 1.
```

I know absolutely nothing about `lxc` and don't know if it should work within a virtualised environment or not?

**Comment by MarcoFalke** [comment]
You could try with docker on fedora (Ubuntu should work as well), which is also described in the docs repository.

**Comment by hebasto** [comment]
@sipsorcery 
> `lxc-execute: gitian: start.c: lxc_spawn: 1616 Failed to find gateway addresses`

It seems lxc network bridge is not setup properly.
In the file `/etc/default/lxc-net` try to replace `LXC_BRIDGE="lxcbr0"` with `LXC_BRIDGE="br0"`.
Reboot. And check the bridge 'br0':
```
ip link show type bridge
```

**Comment by sipsorcery** [comment]
@hebasto my `/etc/default/lxc-net` already had `LXC_BRIDGE="br0"`. Full contents minus the comments:

```
USE_LXC_BRIDGE="true"
LXC_BRIDGE="br0"
LXC_ADDR="10.0.1.1"
LXC_NETMASK="255.255.255.0"
LXC_NETWORK="10.0.1.0/24"
LXC_DHCP_RANGE="10.0.1.2,10.0.1.254"
LXC_DHCP_MAX="253"
```
And
```
admin@btc-gitian:~$ ip link show type bridge
3: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:00:00:00 brd ff:ff:ff:ff:ff:ff
```

**Comment by sipsorcery** [comment]
Closing as I suspect I'm doing this all wrong. Don't think I should need lxc. Will get a better grip on what `gitian-build.py` is doing.
